"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const catalog = require("../client/js/providers/grsModelCatalog");
const legacy = require("../client/js/providers/grsLegacyAdapter");
const { buildGrsHttpRequest, normalizeGrsConfig } = require("../client/js/providers/grsProvider");

const CURRENT_IDS = ["gpt-image-2", "gpt-image-2-vip", "nano-banana-pro", "nano-banana-fast", "nano-banana-pro-vt", "nano-banana-2", "nano-banana-2-lite", "nano-banana-pro-cl", "nano-banana-2-cl", "nano-banana-2-2k-cl", "nano-banana-pro-vip", "nano-banana-pro-4k-vip", "nano-banana-2-4k-cl"];
const SIZES = { "gpt-image-2": ["1K"], "gpt-image-2-vip": ["1K", "2K", "4K"], "nano-banana-pro": ["1K", "2K", "4K"], "nano-banana-fast": null, "nano-banana-pro-vt": ["1K", "2K", "4K"], "nano-banana-2": ["1K", "2K", "4K"], "nano-banana-2-lite": null, "nano-banana-pro-cl": ["1K"], "nano-banana-2-cl": ["1K"], "nano-banana-2-2k-cl": ["2K"], "nano-banana-pro-vip": ["1K", "2K"], "nano-banana-pro-4k-vip": ["4K"], "nano-banana-2-4k-cl": ["4K"] };
const COSTS = { "gpt-image-2": 600, "gpt-image-2-vip": 2000, "nano-banana-pro": 1800, "nano-banana-fast": 440, "nano-banana-pro-vt": 1800, "nano-banana-2": 1200, "nano-banana-2-lite": 440, "nano-banana-pro-cl": 10000, "nano-banana-2-cl": 6000, "nano-banana-2-2k-cl": 9000, "nano-banana-pro-vip": 10000, "nano-banana-pro-4k-vip": 18000, "nano-banana-2-4k-cl": 13000 };

test("current image model selector catalog contains exactly the current thirteen image models", () => assert.deepEqual(catalog.GRS_MODEL_CATALOG.map((model) => model.id).sort(), CURRENT_IDS.slice().sort()));
test("nano-banana-2-lite is current while nano-banana is legacy-only metadata", () => { assert.equal(catalog.getGrsModel("nano-banana-2-lite").currentCatalogListed, true); assert.equal(catalog.getGrsModel("nano-banana").currentCatalogListed, false); assert.equal(catalog.getGrsModel("nano-banana").legacyDocumented, true); assert.equal(catalog.GRS_MODEL_CATALOG.some((model) => model.id === "nano-banana"), false); });
test("current resolution and optional credit metadata matches the supplied current catalog", () => CURRENT_IDS.forEach((id) => { assert.deepEqual(catalog.getGrsModel(id).currentCatalogSupportedImageSizes, SIZES[id]); assert.equal(catalog.getGrsModel(id).currentCatalogCostCredits, COSTS[id]); }));
test("models with no confirmed current size badge omit New API imageSize", () => { ["nano-banana-fast", "nano-banana-2-lite"].forEach((id) => { const model = catalog.getGrsModel(id); assert.equal(model.supportedImageSizes, null); const body = JSON.parse(buildGrsHttpRequest({ modelId: id, prompt: "p", imageSize: null, references: [] }, normalizeGrsConfig({ modelId: id }), "k", model).body); assert.equal("imageSize" in body, false); }); });
test("capability sources are layered as current, New API, and Legacy API", () => CURRENT_IDS.forEach((id) => { const model = catalog.getGrsModel(id); assert.ok(model.currentCatalogCapabilities); assert.equal(model.newApiCapabilities.requestImageField, "images"); assert.equal(model.legacyApiCapabilities.requestImageField, "urls"); }));
test("only Nano 2 documented series receives extended ratios", () => { ["nano-banana-2", "nano-banana-2-cl", "nano-banana-2-2k-cl", "nano-banana-2-4k-cl"].forEach((id) => assert.deepEqual(catalog.getGrsModel(id).supportedAspectRatios, catalog.GRS_NANO_2_EXTENDED_RATIOS)); assert.deepEqual(catalog.getGrsModel("nano-banana-pro").supportedAspectRatios, catalog.GRS_STANDARD_RATIOS); });
test("GPT Legacy metadata records multiple references and quality only for Legacy", () => { const model = catalog.getGrsModel("gpt-image-2"); assert.equal(model.legacyApiCapabilities.supportsMultipleReferences, true); assert.deepEqual(model.legacyApiCapabilities.quality, ["auto", "low", "medium", "high"]); assert.equal(model.newApiCapabilities.quality, undefined); });

function image(id) { return { id, base64: id.toUpperCase() }; }
test("Nano Legacy maps main image first and references to urls[]", () => { const request = { modelId: "nano-banana-2", prompt: "p", aspectRatio: "auto", imageSize: "2K", imageInputs: { mainImage: image("main"), referenceImages: [image("r1"), image("r2")] } }; const http = legacy.buildGrsLegacyGenerationRequest(request, { baseUrl: "https://grsaiapi.com", imageSize: "1K" }, "k", catalog.getGrsModel("nano-banana-2")); assert.equal(http.url, "https://grsaiapi.com/v1/draw/nano-banana"); assert.deepEqual(JSON.parse(http.body), { model: "nano-banana-2", prompt: "p", aspectRatio: "auto", urls: ["MAIN", "R1", "R2"], webHook: "", shutProgress: false, imageSize: "2K" }); });
test("GPT Legacy maps multiple images to urls[] and quality", () => { const request = { modelId: "gpt-image-2", prompt: "p", aspectRatio: "1024x1024", quality: "high", imageInputs: { mainImage: image("main"), referenceImages: [image("r1")] } }; const http = legacy.buildGrsLegacyGenerationRequest(request, { baseUrl: "https://grsaiapi.com" }, "k", catalog.getGrsModel("gpt-image-2")); assert.equal(http.url, "https://grsaiapi.com/v1/draw/completions"); assert.deepEqual(JSON.parse(http.body).urls, ["MAIN", "R1"]); assert.equal(JSON.parse(http.body).quality, "high"); });
test("Legacy result adapter uses POST /v1/draw/result and unwraps code/data", () => { const request = legacy.buildGrsLegacyResultRequest("https://grsaiapi.com", "task-1", "k"); assert.equal(request.url, "https://grsaiapi.com/v1/draw/result"); assert.equal(request.method, "POST"); assert.deepEqual(JSON.parse(request.body), { id: "task-1" }); assert.equal(legacy.parseGrsLegacyResult({ code: 0, data: { id: "task-1", status: "succeeded", results: [{ url: "https://x/a.png" }] }, msg: "success" }).status, "succeeded"); });
